project:
  type: book
  output-dir: docs

book:
  title: "MicroAgroBiome"
  author:
    - name: Haydeé Peruyero
      degrees: PhD
      url: https://haydeeperuyero.github.io/
      orcid: https://orcid.org/0000-0002-4820-1798
      email: haydeeperuyero@unam.mx
      affiliations:
        - name: ENES-Juriquilla, UNAM
          country: Mexico
          url: https://www.enesjuriquilla.unam.mx/?page_id=11292 
    - name: Evelia Coss
      degrees: PhD
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      affiliations:
        - name: ENES-Juriquilla, UNAM
          country: Mexico
          url: https://www.enesjuriquilla.unam.mx/  
  date: "09/21/2025"
  page-navigation: true
  chapters:
  - index.qmd
  - part: "**Sección 1** - "
    chapters:
    - intro.qmd
    - Cap1.qmd
  - part: "**Sección 2** - "
    chapters:
    - Cap2A.qmd
  - part: "**Sección 3** - "
    chapters:
    - Cap3A.qmd
  - part: "**Sección 4** - "
    chapters:
    - Cap5A.qmd
    - Cap5B.qmd
  - part: "**Sección 5** -"
    chapters:
    - Cap4A.qmd
  - part: "**Sección 6** "
    chapters:
    - Cap6A.qmd
  # Information
  site-url: https://github.com/MicroAgroBiome/MicroAgroBiome_bioinfo2026_libro # 📍URL del sitio completo Rladies Mexico
  repo-url: https://github.com/MicroAgroBiome/MicroAgroBiome_bioinfo2026_libro  # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "logos/favicon.png" # icono de la pagina en pestana

format:
  html:
    logo: "logos/favicon.png"
    toc-depth: 4
    number-depth: 3
    # css
    css: styles.css
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      # dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

lang: es # configuración en Español

execute:
  error: true # Se aceptan errores
  message: false # Silenciar mensajes de salida
  echo: true
